#!/bin/bash

CONFIG="$HOME/.config/newm/waybar/config"
STYLE="$HOME/.config/newm/waybar/style.css"

if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
